name: 📊 Build Submission (Help Validate Formulas!)
description: Submit your in-game build and stats to help improve simulation accuracy
title: "[BUILD] Hunter: YOUR_HUNTER - Level: YOUR_LEVEL"
labels: ["build-submission", "validation-data"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for contributing to formula validation! 🎉
        
        By submitting your **real in-game stats**, you help us fine-tune the simulation formulas to match the game exactly. The more data points we have, the more accurate the optimizer becomes!
        
        **Please fill out as much as you can** - even partial data is helpful!
        
        📸 **Where to find these stats**: Open your Attributes page in-game and look at the stats panel on the right side.

  - type: dropdown
    id: hunter
    attributes:
      label: Hunter
      description: Which hunter is this build for?
      options:
        - Borge
        - Knox
        - Ozzy
    validations:
      required: true

  - type: input
    id: level
    attributes:
      label: Hunter Level
      description: Your current hunter level
      placeholder: "69"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 🎯 Combat Stats (from Attributes Page)

  - type: input
    id: enemies_killed_best
    attributes:
      label: Best Run Enemies Killed
      description: Highest number of enemies killed in a single run
      placeholder: "1,234"
    validations:
      required: true

  - type: input
    id: enemies_killed_avg
    attributes:
      label: Avg Run Enemies Killed
      description: Average enemies killed per run
      placeholder: "1,100"
    validations:
      required: true

  - type: input
    id: highest_stage
    attributes:
      label: Highest Stage
      description: Your all-time highest stage reached
      placeholder: "300"
    validations:
      required: true

  - type: input
    id: highest_stage_avg
    attributes:
      label: Highest Stage Run Avg
      description: Your average stage for runs (shown on attributes page)
      placeholder: "295.5"
    validations:
      required: true

  - type: input
    id: run_avg_time
    attributes:
      label: Run Avg Time
      description: Average time per run (format HH:MM:SS or seconds)
      placeholder: "40:00 or 2400"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 💎 Resource Gains (from Attributes Page)
        
        **Borge**: Obsidian / Behlium / Hellish-Biomatter
        **Knox**: Glacium / Quartz / Tesseracts  
        **Ozzy**: Farahyte Ore / Galvarium / Vectid Crystals

  - type: input
    id: common_resource_best
    attributes:
      label: Common Resource - Best Run
      description: "Borge: Obsidian | Knox: Glacium | Ozzy: Farahyte Ore"
      placeholder: "4.5B"
    validations:
      required: true

  - type: input
    id: common_resource_avg
    attributes:
      label: Common Resource - Avg
      description: Average common resource per run
      placeholder: "4.2B"
    validations:
      required: true

  - type: input
    id: uncommon_resource_best
    attributes:
      label: Uncommon Resource - Best Run
      description: "Borge: Behlium | Knox: Quartz | Ozzy: Galvarium"
      placeholder: "1.2B"
    validations:
      required: true

  - type: input
    id: uncommon_resource_avg
    attributes:
      label: Uncommon Resource - Avg
      description: Average uncommon resource per run
      placeholder: "1.1B"
    validations:
      required: true

  - type: input
    id: rare_resource_best
    attributes:
      label: Rare Resource - Best Run
      description: "Borge: Hellish-Biomatter | Knox: Tesseracts | Ozzy: Vectid Crystals"
      placeholder: "500M"
    validations:
      required: true

  - type: input
    id: rare_resource_avg
    attributes:
      label: Rare Resource - Avg
      description: Average rare resource per run
      placeholder: "450M"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## ⭐ XP Gains

  - type: input
    id: xp_best
    attributes:
      label: XP Gained - Best Run
      description: Highest XP gained in a single run
      placeholder: "6.5B"
    validations:
      required: true

  - type: input
    id: xp_avg
    attributes:
      label: XP Gained - Avg
      description: Average XP per run
      placeholder: "5.9B"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 🛠️ Your Build Configuration

  - type: textarea
    id: build_json
    attributes:
      label: Build JSON (from Save/Export)
      description: |
        Paste your build JSON here. You can export this from the optimizer's Save feature, 
        or copy from `%LOCALAPPDATA%\HunterSimOptimizer\my_HUNTER_build.json`
      placeholder: |
        {
          "hunter": "Borge",
          "level": 69,
          "stats": { "hp": 375, "power": 324, ... },
          "talents": { ... },
          "attributes": { ... },
          ...
        }
      render: json
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## 📈 Simulation Results (Optional but Helpful!)

  - type: textarea
    id: sim_results
    attributes:
      label: Simulation Results
      description: |
        If you've run the optimizer with this build, paste the sim results here.
        This shows us exactly how close (or far off) our simulation is from reality!
      placeholder: |
        From the optimizer's "Compare" tab or results:
        
        Sim Avg Stage: 300.0
        Sim Max Stage: 300
        Sim Avg Time: 2380s
        Sim Avg Loot (Common): 4.3B
        Sim Avg XP: 5.7B
        
        Accuracy: 97.5% OPTIMAL

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: |
        Any other information that might be helpful:
        - Stages where you die most often
        - Bosses that seem particularly hard/easy
        - Mechanics that don't seem to work as expected
        - Screenshot links
      placeholder: "I usually die around stage 295 to the Stage 300 boss..."

  - type: checkboxes
    id: consent
    attributes:
      label: Data Usage Consent
      description: |
        Your build data will be used to improve simulation accuracy.
      options:
        - label: I consent to my build being used for formula validation
          required: true
        - label: I'm okay with my build being included in test datasets (anonymized)
